### ISSUE TITLE
OSError: libarchive.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JefferyKu** [ArthurMoore85/pi_romulus#12] opened 2017-10-13 06:30 UTC
Hi,
I have no idea about this when I execute `python romulus.py`. How to solve this problem? Thanks.
`  1 Traceback (most recent call last):
  2   File "romulus.py", line 9, in <module>
  3     from forms import SearchForm
  4   File "/home/pi/pi_romulus/forms/__init__.py", line 8, in <module>
  5     from forms.search import SearchForm
  6   File "/home/pi/pi_romulus/forms/search.py", line 11, in <module>
  7     from scraping.scraper import Scraper
  8   File "/home/pi/pi_romulus/scraping/scraper.py", line 16, in <module>
  9     from io_utils.compression import Compression
 10   File "/home/pi/pi_romulus/io_utils/compression.py", line 10, in <module>
 11     import libarchive.public
 12   File "/usr/local/lib/python2.7/dist-packages/libarchive/public.py", line 1    , in <module>
 13     from libarchive.adapters.archive_read import \
 14   File "/usr/local/lib/python2.7/dist-packages/libarchive/adapters/archive_r    ead.py", line 7, in <module>
 15     import libarchive.calls.archive_read
 16   File "/usr/local/lib/python2.7/dist-packages/libarchive/calls/archive_read    .py", line 3, in <module>
 17     from libarchive.library import libarchive
 18   File "/usr/local/lib/python2.7/dist-packages/libarchive/library.py", line     16, in <module>
 19     libarchive = ctypes.cdll.LoadLibrary(_FILEPATH)   
 20   File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
 21     return self._dlltype(name)
 22   File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
 23     self._handle = _dlopen(self._name, mode)
 24 OSError: libarchive.so: cannot open shared object file: No such file or directory`

**Comment by ArthurMoore85** [comment] 2017-10-13 08:21
I suspect that you may have forgotten to install the libarchive dependency.
Can you try entering the following into the terminal:
`sudo apt-get install libarchive-dev`
Then attempt to run `python romulus.py` again

**Comment by JefferyKu** [comment] 2017-10-18 03:46
Hi,
The lib resolve the matter. But, I have the other question about the application scenario. The screen pops up a window when I execute `python romulus.py` this command. Then, I search the keyword to get the results. I select a rom and push ok to run downing. Above all are fine. 
However, I check the rom folder. I see only a 
`get-download.php?gid=33721&token=72dbc67188af33309fed3d9eeefe4920&mirror_available=true`  address without the prefix of the site. 
Is this a bug or a normal condition? Thanks.

**Comment by ArthurMoore85** [comment] 2017-10-18 13:08
I'm unsure what the issue is that you are witnessing.
What system are you running this on? Also, are the ROMs getting downloaded.
It's also recommended that you pull in the latest copy of this repository by running:

> `git pull origin master`
from inside the directory, as there are some new changes and bugfixes in there.

**Comment by ArthurMoore85** [comment] 2017-12-12 12:21
Issue is resolved with latest update

**Closed by ArthurMoore85** 2017-12-12 12:21 UTC
