### ISSUE TITLE
download the secret of monkey islands

### ISSUE THREAD

**Issue by pietrondo** [ArthurMoore85/pi_romulus#30] opened 2018-06-05 16:41 UTC
this is the logs
thx 

 >   File "romulus.py", line 43, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)    
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/local/lib/python2.7/dist-packages/npyscreen/apNPSApplicationManaged.py", line 174, in main
    self._THISFORM.afterEditing()
  File "/home/pi/RetroPie-Setup/pi_romulus/forms/results.py", line 30, in afterEditing
    selection = self.parentApp.RESULTS[selected_option]
KeyError: None

**Comment by ArthurMoore85** [comment] 2018-06-05 20:28
This issue was caused by having not selected a ROM.
In order to download the ROM, select which one you want, then hit ENTER. After you hit Enter, the selection text will become bold, then select OK to continue.

It's quite right that this should not have resulted in a crash with KeyError, and this has been fixed and merged into master. In the future, not selecting a ROM but selecting OK will result in a message being shown to inform you than nothing was selected. This message is timed and will disappear after a few seconds.

**Comment by pietrondo** [comment] 2018-06-05 20:30
Yep. And is possible to have s progression bar ?
And After... Could ne userfull a web interface.
Thx a lot for your work. It is very userfull

Il mar 5 giu 2018, 22:28 Arthur Moore <notifications@github.com> ha scritto:

**Comment by ArthurMoore85** [comment] 2018-06-05 20:37
You have hit on a couple of points I have actually been looking at.
Currently the app is built using the npyscreen library which provides the interface. Unfortunaly it's very limited in capability and progressbars are something that isn't possible without hacking that library.

The web interface is actually something that I am looking into. This will allow me to add some more features such as logging previous downloads, some art perhaps, downloading away from the Pi (using for instance a mobile device) and maybe even library management.
That would be a big task to do, as it would be an almost complete rewrite. I'm more than prepared to do that, but this will take some time to do

**Closed** 2018-06-06 13:45 UTC
Labels: bug
